package com.lib.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigDecimal;
import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.title
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.isbn
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String isbn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.cover_img
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String coverImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.description
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.author
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_copy_number
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer bookCopyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publisher
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.publication_place
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */

    private String publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.user_id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.created_time
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */

    @JsonFormat(shape = JsonFormat.Shape.STRING,pattern ="yyyy-MM-dd HH:mm:ss",timezone ="GMT+8")
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.class
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.title
     *
     * @return the value of book.title
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.title
     *
     * @param title the value for book.title
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.isbn
     *
     * @return the value of book.isbn
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.isbn
     *
     * @param isbn the value for book.isbn
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.cover_img
     *
     * @return the value of book.cover_img
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getCoverImg() {
        return coverImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.cover_img
     *
     * @param coverImg the value for book.cover_img
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setCoverImg(String coverImg) {
        this.coverImg = coverImg == null ? null : coverImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.description
     *
     * @return the value of book.description
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.description
     *
     * @param description the value for book.description
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.author
     *
     * @return the value of book.author
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.author
     *
     * @param author the value for book.author
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.class_number
     *
     * @return the value of book.class_number
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_copy_number
     *
     * @return the value of book.book_copy_number
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Integer getBookCopyNumber() {
        return bookCopyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_copy_number
     *
     * @param bookCopyNumber the value for book.book_copy_number
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setBookCopyNumber(Integer bookCopyNumber) {
        this.bookCopyNumber = bookCopyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publisher
     *
     * @return the value of book.publisher
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publisher
     *
     * @param publisher the value for book.publisher
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.publish_date
     *
     * @return the value of book.publish_date
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.publish_date
     *
     * @param publishDate the value for book.publish_date
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setPublishDate(String publishDate) {
        this.publishDate = publishDate == null ? null : publishDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.user_id
     *
     * @return the value of book.user_id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.user_id
     *
     * @param userId the value for book.user_id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.created_time
     *
     * @return the value of book.created_time
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.created_time
     *
     * @param createdTime the value for book.created_time
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Integer getCategory() {
        return category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }
}