package com.lib.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class borrowReturnBooks {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_return_books.id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_return_books.reader_id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer readerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_return_books.operation
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_return_books.borrow_time
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING,pattern ="yyyy-MM-dd HH:mm:ss",timezone ="GMT+8")
    private Date borrowTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_return_books.return_time
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING,pattern ="yyyy-MM-dd HH:mm:ss",timezone ="GMT+8")
    private Date returnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_return_books.user_id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column borrow_return_books.status
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer status;


    @JsonFormat(shape = JsonFormat.Shape.STRING,pattern ="yyyy-MM-dd HH:mm:ss",timezone ="GMT+8")
    private Date planTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_return_books.id
     *
     * @return the value of borrow_return_books.id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_return_books.id
     *
     * @param id the value for borrow_return_books.id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_return_books.reader_id
     *
     * @return the value of borrow_return_books.reader_id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Integer getReaderId() {
        return readerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_return_books.reader_id
     *
     * @param readerId the value for borrow_return_books.reader_id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setReaderId(Integer readerId) {
        this.readerId = readerId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_return_books.borrow_time
     *
     * @return the value of borrow_return_books.borrow_time
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Date getBorrowTime() {
        return borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_return_books.borrow_time
     *
     * @param borrowTime the value for borrow_return_books.borrow_time
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setBorrowTime(Date borrowTime) {
        this.borrowTime = borrowTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_return_books.return_time
     *
     * @return the value of borrow_return_books.return_time
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_return_books.return_time
     *
     * @param returnTime the value for borrow_return_books.return_time
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_return_books.user_id
     *
     * @return the value of borrow_return_books.user_id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_return_books.user_id
     *
     * @param userId the value for borrow_return_books.user_id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column borrow_return_books.status
     *
     * @return the value of borrow_return_books.status
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column borrow_return_books.status
     *
     * @param status the value for borrow_return_books.status
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getBookId() {
        return bookId;
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    public Date getPlanTime() {
        return planTime;
    }

    public void setPlanTime(Date time) {
        this.planTime = time;
    }
}