package com.lib.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Reader implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.email
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.username
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */

    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.password
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.reader_name
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String readerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.deposit
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private BigDecimal deposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.creditmoney
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private BigDecimal creditmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.isValid
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private Integer isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reader.salt
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    private String salt;

    private Integer age = null;

    private String gender;

    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.id
     *
     * @return the value of reader.id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.id
     *
     * @param id the value for reader.id
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.email
     *
     * @return the value of reader.email
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.email
     *
     * @param email the value for reader.email
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.password
     *
     * @return the value of reader.password
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.password
     *
     * @param password the value for reader.password
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.reader_name
     *
     * @return the value of reader.reader_name
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getReaderName() {
        return readerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.reader_name
     *
     * @param readerName the value for reader.reader_name
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setReaderName(String readerName) {
        this.readerName = readerName == null ? null : readerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.deposit
     *
     * @return the value of reader.deposit
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public BigDecimal getDeposit() {
        return deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.deposit
     *
     * @param deposit the value for reader.deposit
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.creditmoney
     *
     * @return the value of reader.creditmoney
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public BigDecimal getCreditmoney() {
        return creditmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.creditmoney
     *
     * @param creditmoney the value for reader.creditmoney
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setCreditmoney(BigDecimal creditmoney) {
        this.creditmoney = creditmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.isValid
     *
     * @return the value of reader.isValid
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.isValid
     *
     * @param isvalid the value for reader.isValid
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reader.salt
     *
     * @return the value of reader.salt
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reader.salt
     *
     * @param salt the value for reader.salt
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }
}