package com.lib.mapper;

import com.lib.controller.vo.BookShowVO;
import com.lib.entity.Book;
import com.lib.entity.Reader;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;

@Mapper
public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    Book selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    int updateByPrimaryKey(Book record);

    List<Book> selectAllByKeyWordAndCategory(@Param("keyWord") String keyWord, @Param("category") Integer category);

    int editBook(@Param("id") Integer id, @Param("title") String title, @Param("isbn") String isbn, @Param("urlCover") String urlCover, @Param("author") String author, @Param("price") BigDecimal price, @Param("category") Integer category, @Param("bookCopyNumber") Integer bookCopyNumber, @Param("publisher") String publisher, @Param("publishDate") String publishDate, @Param("userId") Integer userId, @Param("createdTime") Date createdTime, @Param("description") String description);

    List<Book> selectByISBN(@Param("isbn") String isbn);

    List<Integer> selectCategoryByPrimaryKey(@Param("id") Integer id);

    List<Book> selectAllByCategory(@Param("category") Integer id);

    Integer selectBookIdByTitle(@Param("title") String title);

    List<Map<Integer, BigDecimal>> getCopyCount();

    List<Book> selectAllOrderByTime();

    int incrCopyCountById(@Param("id") Integer id);

    int decrCopyCountById(@Param("id") Integer id);

    List<BookShowVO> batchSelectByPrimaryKey(Set<Integer> ids);

    List<Book> getAllBookByCategories(List<Integer> Categories);
}