package com.lib.mapper;

import com.lib.entity.Reader;
import com.lib.entity.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 05 13:25:15 CST 2022
     */
    List<User> selectAll();

    User selectByPrimaryKey(@Param("id") Integer id);

    List<User> selectUserByEmail(@Param("email") String email);

    List<User> selectUserByLoginName(@Param("loginName") String loginName);

    int updatePasswordAndSaltByEmail(@Param("email") String email,@Param("salt") String salt,@Param("password") String password);

    int updateAdminInfo(@Param("id") Integer id, @Param("salt") String salt, @Param("password") String password, @Param("gender") String gender, @Param("age") Integer age, @Param("email") String email, @Param("introduce") String introduce);

}